name: Linting

on: [push, pull_request]

jobs:
  lint_code:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm install --user yarn
          yarn install
      - name: Run Standard lint
        run: yarn run lint
      - name: Run type check tsc
        run: yarn run typecheck